// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveySystem.Data;

#nullable disable

namespace SurveySystem.Migrations
{
    [DbContext(typeof(KPI_DbContext))]
    partial class KPI_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurveySystem.Models.TblKPI", b =>
                {
                    b.Property<int>("KPIDNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KPIDNum"));

                    b.Property<int>("DepNo")
                        .HasColumnType("int");

                    b.Property<string>("KPIDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("MeasurementUnit")
                        .HasColumnType("bit");

                    b.Property<int>("TargetedValue")
                        .HasColumnType("int");

                    b.HasKey("KPIDNum");

                    b.ToTable("TblKPI");
                });
#pragma warning restore 612, 618
        }
    }
}
